[package]
name = "luapp"
version = "0.5.0"
authors = ["Alexey Minchakov <lexaaim@gmail.com>"]
edition = "2018"

[build-dependencies]
lalrpop = "0.19.1"

[dependencies]
lalrpop-util = "0.19.1"
regex = "1"
phf = { version = "0.8", features = ["macros"] }
